#!/bin/sh

crontab ~/current/crontab
echo "set crontab"

cd $HOME/code
ln -s ~/etc/vimpusher.www/config/database.yml ~/current/config/database.yml
ln -s ~/etc/vimpusher.www/config/oauth.yml ~/current/config/oauth.yml
ln -s ~/etc/vimpusher.www/config/redis.yml ~/current/config/redis.yml
ln -s ~/etc/vimpusher.www/config/initializers/resque_auth.rb ~/current/config/initializers/resque_auth.rb
echo "made a symbolic link to the configuration file"
