#!/bin/sh

# Set cron only www, not resqueworker
hostname | grep www 1>/dev/null && crontab ~/current/crontab && echo "set crontab"

# Even rubyworker must create symbolic link otherwise rails init will be failed.
cd $HOME/code
ln -s ~/data/vimpusher.www/config/database.yml ~/current/config/database.yml
ln -s ~/data/vimpusher.www/config/oauth.yml ~/current/config/oauth.yml
ln -s ~/data/vimpusher.www/config/redis.yml ~/current/config/redis.yml
ln -s ~/data/vimpusher.www/config/initializers/resque_auth.rb ~/current/config/initializers/resque_auth.rb
echo "made a symbolic link to the configuration file"
